- name: Create directory
  ansible.builtin.file:
    state: directory
    path: "{{ cf_whitelist_dir }}"
    group: root
    owner: root
    mode: "0755"

- name: Render systemd service
  ansible.builtin.template:
    src: cf-whitelist.service.j2
    dest: /etc/systemd/system/cf-whitelist.service.j2
    owner: root
    group: root
    mode: "0644"

- name: Render systemd timer
  ansible.builtin.template:
    src: cf-whitelist.timer.j2
    dest: /etc/systemd/system/cf-whitelist.timer.j2
    owner: root
    group: root
    mode: "0644"

- name: Start timer
  ansible.builtin.systemd:
    name: cf-whitelist.timer
    state: started
    enabled: true
    daemon_reload: true
